version: '3'
services:

  front-envoy:
    container_name: front-envoy
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "18000"
      - "8001"
    ports:
      - "18000:18000"
      - "8001:8001"

  authz:
    container_name: authz
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      envoymesh:
        aliases:
          - authz
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: on-failure
    expose:
      - "8080"
      - "8081"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - redis
      - service1
      - front-envoy

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      envoymesh:
        aliases:
          - postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: authz
      POSTGRES_USER: authz
      POSTGRES_PASSWORD: password

  service1:
    container_name: service1
    build:
      context: .
      dockerfile: Dockerfile.service
    networks:
      envoymesh:
        aliases:
          - service1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    expose:
      - "8002"
    ports:
      - "8002:8002"
    depends_on:
      - front-envoy
      - redis

  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    networks:
      envoymesh:
        aliases:
          - redis
    expose:
      - "6379"
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis'

networks:
  envoymesh:
    name: envoymesh

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
