version: '2'
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "18000"
      - "8001"
    ports:
      - "18000:18000"
      - "8001:8001"

  authz:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      envoymesh:
        aliases:
          - authz
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    expose:
      - "8080"
      - "8081"
    ports:
      - "8080:8080"

  service1:
    build:
      context: .
      dockerfile: Dockerfile.service
    networks:
      envoymesh:
        aliases:
          - service1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    expose:
      - "8002"
    ports:
      - "8002:8002"

  redis:
    image: 'bitnami/redis:latest'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    networks:
      envoymesh:
        aliases:
          - redis
    expose:
      - "6379"
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis'

networks:
  envoymesh: {}

volumes:
  redis_data:
    driver: local
