version: '2'
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "18000"
      - "8001"
    ports:
      - "18000:18000"
      - "8001:8001"

  authz:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      envoymesh:
        aliases:
          - authz
    expose:
      - "8080"
    ports:
      - "8080:8080"

  service1:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - "8002"
    ports:
      - "8002:8002"

networks:
  envoymesh: {}
